#!/bin/sh
#
# For first time installs

eval "git --version" > /dev/null
if [ $? -ne 0 ]; then
    echo "Git not installed. Aborting"
    exit $?
fi

eval "ruby --version" > /dev/null
if [ $? -ne 0 ]; then
    echo "Ruby not installed. Aborting"
    exit $?
fi

eval "clang --version" > /dev/null
if [ $? -ne 0 ]; then
    echo "Clang not installed. Aborting"
    exit $?
fi


git submodule update --init --recursive
rake install
cd $HOME/.vim/bundle/YouCompleteMe/
./install.sh --clang-completer
cd -
